services:
  - type: web
    name: fastapi-postgres-render
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fastapi-db
          property: connectionString

databases:
  - name: fastapi-db
    databaseName: fastapi
    user: fastapi
